// Supported language list
const languages = {
    'af-ZA': 'Afrikaans (South Africa)',
    'ar-XA': 'Arabic (Gulf)',
    'bn-IN': 'Bengali (India)',
    'cs-CZ': 'Czech (Czech Republic)',
    'da-DK': 'Danish (Denmark)',
    'de-DE': 'German (Germany)',
    'el-GR': 'Greek (Greece)',
    'en-AU': 'English (Australia)',
    'en-GB': 'English (United Kingdom)',
    'en-IN': 'English (India)',
    'en-US': 'English (United States)',
    'es-ES': 'Spanish (Spain)',
    'es-US': 'Spanish (United States)',
    'fi-FI': 'Finnish (Finland)',
    'fil-PH': 'Filipino (Philippines)',
    'fr-CA': 'French (Canada)',
    'fr-FR': 'French (France)',
    'hi-IN': 'Hindi (India)',
    'hu-HU': 'Hungarian (Hungary)',
    'id-ID': 'Indonesian (Indonesia)',
    'it-IT': 'Italian (Italy)',
    'ja-JP': 'Japanese (Japan)',
    'ko-KR': 'Korean (South Korea)',
    'nb-NO': 'Norwegian (Norway)',
    'nl-NL': 'Dutch (Netherlands)',
    'pl-PL': 'Polish (Poland)',
    'pt-BR': 'Portuguese (Brazil)',
    'pt-PT': 'Portuguese (Portugal)',
    'ru-RU': 'Russian (Russia)',
    'sk-SK': 'Slovak (Slovakia)',
    'sv-SE': 'Swedish (Sweden)',
    'ta-IN': 'Tamil (India)',
    'tr-TR': 'Turkish (Turkey)',
    'uk-UA': 'Ukrainian (Ukraine)',
    'vi-VN': 'Vietnamese (Vietnam)',
    'zh-CN': 'Chinese (Mandarin, Simplified)',
    'zh-HK': 'Chinese (Cantonese, Traditional)',
    'zh-TW': 'Chinese (Mandarin, Traditional)'
};

module.exports = languages;
